# Generated by Django 5.1.15 on 2026-04-11 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UPVOTE_EXPERIENCE', 'Upvote on Experience'), ('COMMENT_ON_EXPERIENCE', 'Comment on Experience'), ('REPLY_TO_COMMENT', 'Reply to Comment'), ('ATTRACTION_APPROVED', 'Attraction Approved'), ('EXPERIENCE_APPROVED', 'Experience Approved'), ('EXPERIENCE_REJECTED', 'Experience Rejected')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('related_experience_id', models.IntegerField(blank=True, null=True)),
                ('related_comment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
