# Generated by Django 5.1.15 on 2026-04-18 18:32

from django.db import migrations, models


def clear_guest_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="GUEST").update(role="USER")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_guest_role, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
