# Generated by Django 5.1.15 on 2026-04-18 18:32

from django.db import migrations, models


def truncate_long_comments(apps, schema_editor):
    Comment = apps.get_model("interactions", "Comment")
    for c in Comment.objects.exclude(text__exact="").iterator(chunk_size=500):
        if len(c.text) > 1000:
            c.text = c.text[:1000]
            c.save(update_fields=["text"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_align_plan_v1'),
    ]

    operations = [
        migrations.RunPython(truncate_long_comments, noop_reverse),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
