# Generated by Django 5.1.15 on 2026-04-18 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_transport_submitted_by_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_attractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_destinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
